// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebsiteBanHang.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250520173756_nhanvien2")]
    partial class nhanvien2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebsiteBanHang.Models.CTHD", b =>
                {
                    b.Property<int>("SoHD")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaSP")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("MaKho")
                        .HasColumnType("int");

                    b.Property<long>("DonGia")
                        .HasColumnType("bigint");

                    b.Property<int>("SL")
                        .HasColumnType("int");

                    b.HasKey("SoHD", "MaSP", "MaKho");

                    b.HasIndex("MaKho", "MaSP");

                    b.ToTable("CTHDs");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.DSAnh", b =>
                {
                    b.Property<int>("MaAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAnh"));

                    b.Property<int>("MaSP")
                        .HasColumnType("int");

                    b.Property<string>("UrlAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaAnh");

                    b.HasIndex("MaSP");

                    b.ToTable("DSAnhs");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDM"));

                    b.Property<bool>("TTHienThi")
                        .HasColumnType("bit");

                    b.Property<string>("TenDM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDM");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.GioHang.CTGioHang", b =>
                {
                    b.Property<int>("MaGH")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaSP")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<long>("GiaLucThem")
                        .HasColumnType("bigint");

                    b.Property<long>("GiaThemCuoi")
                        .HasColumnType("bigint");

                    b.Property<int?>("SanPhamMaSP")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongThem")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianThemCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianThemDau")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThaiChon")
                        .HasColumnType("bit");

                    b.HasKey("MaGH", "MaSP");

                    b.HasIndex("MaSP");

                    b.HasIndex("SanPhamMaSP");

                    b.ToTable("CTGioHangs");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.GioHang.GioHang", b =>
                {
                    b.Property<int>("MaGH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGH"));

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.HasKey("MaGH");

                    b.HasIndex("MaKH")
                        .IsUnique();

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.HoaDon", b =>
                {
                    b.Property<int>("SoHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoHD"));

                    b.Property<string>("DTNhanHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiGiaoHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KhachHangMaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaPT")
                        .HasColumnType("int");

                    b.Property<int>("MaTT")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGiaoDuKien")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLanDoiTT")
                        .HasColumnType("int");

                    b.HasKey("SoHD");

                    b.HasIndex("KhachHangMaKH");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaPT");

                    b.HasIndex("MaTT");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DTKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinhKH")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaKH");

                    b.HasIndex("UserId");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.NguoiDung.MaXacThuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaSuDung")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaXacNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLanThu")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MaXacThucs");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.NguoiDung.ThongTinNguoiDung", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("WebsiteBanHang.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DTNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinhNV")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaNV");

                    b.HasIndex("UserId");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.PTTT", b =>
                {
                    b.Property<int>("MaPT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPT"));

                    b.Property<bool>("TTHienThi")
                        .HasColumnType("bit");

                    b.Property<string>("TenPT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPT");

                    b.ToTable("PTTTs");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLDanhGia_PhanHoi.AnhDG", b =>
                {
                    b.Property<int>("MaAnhDG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAnhDG"));

                    b.Property<int>("MaDG")
                        .HasColumnType("int");

                    b.HasKey("MaAnhDG");

                    b.HasIndex("MaDG");

                    b.ToTable("AnhDG");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLDanhGia_PhanHoi.DanhGia", b =>
                {
                    b.Property<int>("MaDG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDG"));

                    b.Property<int>("MaKho")
                        .HasColumnType("int");

                    b.Property<int>("MaSP")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDG")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Sao")
                        .HasColumnType("int");

                    b.Property<int>("SoHD")
                        .HasColumnType("int");

                    b.Property<bool?>("TTHienThi")
                        .HasColumnType("bit");

                    b.HasKey("MaDG");

                    b.HasIndex("SoHD", "MaSP", "MaKho")
                        .IsUnique();

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLDanhGia_PhanHoi.LikeDanhGia", b =>
                {
                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaDG")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TGThich")
                        .HasColumnType("datetime2");

                    b.HasKey("MaKH", "MaDG");

                    b.HasIndex("MaDG");

                    b.ToTable("LikeDanhGia");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLDanhGia_PhanHoi.LikePhanHoi", b =>
                {
                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaPH")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TGThich")
                        .HasColumnType("datetime2");

                    b.HasKey("MaKH", "MaPH");

                    b.HasIndex("MaPH");

                    b.ToTable("LikePhanHoi");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLDanhGia_PhanHoi.LikePhanHoiDanhGia", b =>
                {
                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaPHDG")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TGThich")
                        .HasColumnType("datetime2");

                    b.HasKey("MaKH", "MaPHDG");

                    b.HasIndex("MaPHDG");

                    b.ToTable("LikePhanHoiDanhGia");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLDanhGia_PhanHoi.LikeTraLoi", b =>
                {
                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaTL")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TGThich")
                        .HasColumnType("datetime2");

                    b.HasKey("MaKH", "MaTL");

                    b.HasIndex("MaTL");

                    b.ToTable("LikeTraLoi");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLDanhGia_PhanHoi.PhanHoi", b =>
                {
                    b.Property<int>("MaPH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPH"));

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaSP")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayPH")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungPH")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaPH");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaSP");

                    b.ToTable("PhanHoi");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLDanhGia_PhanHoi.PhanHoiDanhGia", b =>
                {
                    b.Property<int>("MaPHDG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPHDG"));

                    b.Property<int>("MaDG")
                        .HasColumnType("int");

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayPHDG")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungPHDG")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaPHDG");

                    b.HasIndex("MaDG");

                    b.HasIndex("MaKH");

                    b.ToTable("PhanHoiDanhGia");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLDanhGia_PhanHoi.TraLoi", b =>
                {
                    b.Property<int>("MaTL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTL"));

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaPH")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTL")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungTL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaTL");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaPH");

                    b.ToTable("TraLoi");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLTonKho.Kho", b =>
                {
                    b.Property<int>("MaKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKho"));

                    b.Property<string>("DCKho")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TTHienThi")
                        .HasColumnType("bit");

                    b.Property<string>("TenKho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKho");

                    b.ToTable("Kho");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLTonKho.TonKho", b =>
                {
                    b.Property<int>("MaKho")
                        .HasColumnType("int");

                    b.Property<int>("MaSP")
                        .HasColumnType("int");

                    b.Property<int>("SLTon")
                        .HasColumnType("int");

                    b.Property<bool>("TTHienThi")
                        .HasColumnType("bit");

                    b.HasKey("MaKho", "MaSP");

                    b.HasIndex("MaSP");

                    b.ToTable("TonKho");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.SanPham", b =>
                {
                    b.Property<int>("MaSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSP"));

                    b.Property<long>("Gia")
                        .HasColumnType("bigint");

                    b.Property<int>("MaDM")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TTDeXuat")
                        .HasColumnType("bit");

                    b.Property<bool>("TTHienThi")
                        .HasColumnType("bit");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlAnh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSP");

                    b.HasIndex("MaDM");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.TrangThai", b =>
                {
                    b.Property<int>("MaTT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTT"));

                    b.Property<bool>("TTHienThi")
                        .HasColumnType("bit");

                    b.Property<string>("TenTT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTT");

                    b.ToTable("TrangThais");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.VaiTroNhanVien", b =>
                {
                    b.Property<int>("MaVTNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVTNV"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.HasKey("MaVTNV");

                    b.HasIndex("MaNV");

                    b.ToTable("VaiTroNhanVien");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.NguoiDung.ThongTinNguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.NguoiDung.ThongTinNguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteBanHang.Models.NguoiDung.ThongTinNguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.NguoiDung.ThongTinNguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebsiteBanHang.Models.CTHD", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.HoaDon", "HoaDon")
                        .WithMany("CTHDs")
                        .HasForeignKey("SoHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteBanHang.Models.QLTonKho.TonKho", "TonKho")
                        .WithMany("CTHDs")
                        .HasForeignKey("MaKho", "MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("TonKho");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.DSAnh", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.SanPham", "SanPham")
                        .WithMany("DSAnh")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.GioHang.CTGioHang", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.GioHang.GioHang", "GioHang")
                        .WithMany("CTGioHangs")
                        .HasForeignKey("MaGH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteBanHang.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebsiteBanHang.Models.SanPham", null)
                        .WithMany("CTGioHangs")
                        .HasForeignKey("SanPhamMaSP");

                    b.Navigation("GioHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.GioHang.GioHang", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.KhachHang", "KhachHang")
                        .WithOne("GioHang")
                        .HasForeignKey("WebsiteBanHang.Models.GioHang.GioHang", "MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.HoaDon", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.KhachHang", null)
                        .WithMany("HoaDons")
                        .HasForeignKey("KhachHangMaKH");

                    b.HasOne("WebsiteBanHang.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebsiteBanHang.Models.PTTT", "PTTT")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaPT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteBanHang.Models.TrangThai", "TrangThai")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaTT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("PTTT");

                    b.Navigation("TrangThai");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.KhachHang", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.NguoiDung.ThongTinNguoiDung", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.NhanVien", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.NguoiDung.ThongTinNguoiDung", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLDanhGia_PhanHoi.AnhDG", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.QLDanhGia_PhanHoi.DanhGia", "DanhGia")
                        .WithMany()
                        .HasForeignKey("MaDG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhGia");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLDanhGia_PhanHoi.DanhGia", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.CTHD", "CTHD")
                        .WithMany()
                        .HasForeignKey("SoHD", "MaSP", "MaKho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CTHD");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLDanhGia_PhanHoi.LikeDanhGia", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.QLDanhGia_PhanHoi.DanhGia", "DanhGia")
                        .WithMany()
                        .HasForeignKey("MaDG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteBanHang.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DanhGia");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLDanhGia_PhanHoi.LikePhanHoi", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebsiteBanHang.Models.QLDanhGia_PhanHoi.PhanHoi", "PhanHoi")
                        .WithMany()
                        .HasForeignKey("MaPH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("PhanHoi");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLDanhGia_PhanHoi.LikePhanHoiDanhGia", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebsiteBanHang.Models.QLDanhGia_PhanHoi.PhanHoiDanhGia", "PhanHoiDanhGia")
                        .WithMany()
                        .HasForeignKey("MaPHDG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("PhanHoiDanhGia");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLDanhGia_PhanHoi.LikeTraLoi", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebsiteBanHang.Models.QLDanhGia_PhanHoi.TraLoi", "TraLoi")
                        .WithMany()
                        .HasForeignKey("MaTL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("TraLoi");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLDanhGia_PhanHoi.PhanHoi", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteBanHang.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLDanhGia_PhanHoi.PhanHoiDanhGia", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.QLDanhGia_PhanHoi.DanhGia", "DanhGia")
                        .WithMany()
                        .HasForeignKey("MaDG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteBanHang.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhGia");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLDanhGia_PhanHoi.TraLoi", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebsiteBanHang.Models.QLDanhGia_PhanHoi.PhanHoi", "PhanHoi")
                        .WithMany()
                        .HasForeignKey("MaPH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("PhanHoi");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLTonKho.TonKho", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.QLTonKho.Kho", "Kho")
                        .WithMany("TonKho")
                        .HasForeignKey("MaKho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebsiteBanHang.Models.SanPham", "SanPham")
                        .WithMany("TonKho")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kho");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.SanPham", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.DanhMuc", "DanhMuc")
                        .WithMany("SanPham")
                        .HasForeignKey("MaDM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.VaiTroNhanVien", b =>
                {
                    b.HasOne("WebsiteBanHang.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.GioHang.GioHang", b =>
                {
                    b.Navigation("CTGioHangs");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.HoaDon", b =>
                {
                    b.Navigation("CTHDs");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.KhachHang", b =>
                {
                    b.Navigation("GioHang")
                        .IsRequired();

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.PTTT", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLTonKho.Kho", b =>
                {
                    b.Navigation("TonKho");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.QLTonKho.TonKho", b =>
                {
                    b.Navigation("CTHDs");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.SanPham", b =>
                {
                    b.Navigation("CTGioHangs");

                    b.Navigation("DSAnh");

                    b.Navigation("TonKho");
                });

            modelBuilder.Entity("WebsiteBanHang.Models.TrangThai", b =>
                {
                    b.Navigation("HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
